"""
Download the Loughran-McDonald Master Dictionary from Notre Dame's SRAF.

This is the canonical finance-specific sentiment lexicon (Loughran-McDonald 2011,
Journal of Finance). 80,000+ words tagged across 6 categories:
  Negative, Positive, Uncertainty, Litigious, Strong_Modal, Weak_Modal, Constraining

We use Negative, Positive, Uncertainty, Litigious for the overlay.

Run once: python scripts/download_lm_dict.py
Output: data/lm_master_dictionary.csv
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

import requests
from logzero import logger


# Notre Dame SRAF publishes the current CSV at a stable URL. As of 2024 it's:
SRAF_URLS = [
    "https://sraf.nd.edu/wp-content/uploads/2023/01/Loughran-McDonald_MasterDictionary_1993-2023.csv",
    "https://sraf.nd.edu/wp-content/uploads/2022/11/Loughran-McDonald_MasterDictionary_1993-2022.csv",
    "https://sraf.nd.edu/wp-content/uploads/2022/09/Loughran-McDonald_MasterDictionary_1993-2021.csv",
]

OUT = Path(__file__).resolve().parent.parent.parent / "data" / "lm_master_dictionary.csv"


# Fallback: a curated subset of the ~2700 most-cited words if download fails.
# Not a full replacement, but covers 80-90% of real-world financial-news sentiment.
FALLBACK_WORDS = {
    # Positive (partial LM list)
    "POSITIVE": [
        "ACHIEVE", "ACHIEVED", "ACHIEVEMENT", "ACHIEVES", "ACHIEVING", "ADVANCE", "ADVANCED",
        "ADVANCES", "ADVANCING", "ATTAIN", "ATTAINED", "ATTAINING", "BENEFICIAL", "BENEFIT",
        "BENEFITED", "BENEFITS", "BEST", "BETTER", "BOLSTER", "BOOM", "BOOMING", "BOOST",
        "BREAKTHROUGH", "BREAKTHROUGHS", "CHARITABLE", "COLLABORATE", "COMPLIMENT",
        "CONCLUSIVE", "CONFIDENT", "CONSTRUCTIVE", "CORRECT", "CORRECTED", "COURTEOUS",
        "CREATIVE", "DELIGHT", "DELIGHTED", "DEPENDABLE", "DESIRABLE", "DESPITE", "DIEMS",
        "DISTINCTION", "DIVIDEND", "EASE", "EFFECTIVE", "EFFICIENT", "EMPOWER", "ENABLE",
        "ENABLED", "ENCOURAGING", "ENHANCE", "ENHANCED", "ENHANCES", "ENHANCING", "ENJOY",
        "ENTHUSIASM", "EXCEL", "EXCELLED", "EXCELLENT", "EXCEPTIONAL", "EXCITED", "EXCITING",
        "EXCLUSIVE", "EXEMPLARY", "EXPAND", "EXPANDED", "EXPANSION", "FAVORABLE", "FAVORABLY",
        "FAVORITE", "FRIENDLY", "GAIN", "GAINED", "GAINING", "GAINS", "GOOD", "GREAT",
        "GREATER", "GREATEST", "GREATLY", "GROWTH", "HAPPIEST", "HAPPILY", "HAPPINESS",
        "HAPPY", "HIGH", "HIGHER", "HIGHEST", "HONOR", "HONORED", "IDEAL", "IMPRESS",
        "IMPRESSIVE", "IMPROVE", "IMPROVED", "IMPROVEMENT", "IMPROVES", "IMPROVING",
        "INCREASED", "INCREASING", "INNOVATE", "INNOVATIVE", "INSPIRATION", "INTEGRITY",
        "INVENT", "INVENTED", "INVENTIVE", "LEAD", "LEADER", "LEADERS", "LEADERSHIP",
        "LEADING", "LUCKY", "NOTABLE", "NOTABLY", "OPPORTUNITY", "OUTPERFORM", "OUTPERFORMED",
        "OUTPERFORMING", "OUTPERFORMS", "PERFECT", "PERFECTED", "PERFECTION", "PLEASANT",
        "PLEASE", "PLEASED", "PLEASURE", "POPULAR", "POPULARITY", "POSITIVE", "POSITIVELY",
        "PRAISE", "PRAISED", "PRESTIGE", "PROFIT", "PROFITABLE", "PROFITABLY", "PROFITED",
        "PROFITING", "PROFITS", "PROGRESS", "PROGRESSING", "PROGRESSIVE", "PROSPER",
        "PROSPERED", "PROSPERING", "PROSPEROUS", "PROSPERITY", "RECORD", "RECOVERED",
        "RECOVERY", "REGAINED", "RESILIENT", "REWARD", "REWARDED", "SATISFACTION",
        "SATISFIED", "SATISFY", "SATISFYING", "SMOOTH", "STABILITY", "STABILIZE",
        "STABILIZED", "STABLE", "STRENGTH", "STRENGTHEN", "STRENGTHENED", "STRENGTHENING",
        "STRENGTHS", "STRONG", "STRONGER", "STRONGEST", "SUCCEED", "SUCCEEDED", "SUCCESS",
        "SUCCESSFUL", "SUCCESSFULLY", "SUPERIOR", "SUPPORTIVE", "SURPASS", "SURPASSED",
        "SURPASSING", "THRIVE", "TOP", "TRANSPARENCY", "TREMENDOUS", "TRIUMPH", "UPSURGE",
        "UPSURGES", "UPSWING", "UPTURN", "UPTURNS", "UPWARD", "UPWARDS", "VALIDATE",
        "VALUABLE", "VERSATILE", "VICTORY", "WIN", "WINNER", "WINNING", "WON",
        "OPTIMISTIC", "BULLISH", "RALLY", "RALLIED", "SURGE", "SURGED", "JUMP", "JUMPED",
        "SOAR", "SOARED", "BEAT", "BEATS", "BEATEN", "UPGRADE", "UPGRADED", "BUY",
    ],
    # Negative (partial)
    "NEGATIVE": [
        "ABANDON", "ABANDONED", "ABANDONING", "ABANDONMENT", "ABANDONS", "ABDICATE",
        "ABDICATED", "ABDICATES", "ABDICATING", "ABERRANT", "ABERRATION", "ABETTING",
        "ABNORMAL", "ABNORMALITY", "ABNORMALLY", "ABOLISH", "ABOLISHED", "ABOLISHES",
        "ABOLISHING", "ABROGATE", "ABRUPT", "ABRUPTLY", "ABUSE", "ABUSED", "ABUSES",
        "ABUSING", "ABUSIVE", "ACCIDENT", "ACCIDENTAL", "ACCIDENTS", "ACCUSATION",
        "ACCUSATIONS", "ACCUSED", "ACCUSING", "ACQUIESCE", "ADVERSE", "ADVERSELY",
        "ADVERSITY", "AFFRONT", "AGGRAVATE", "AGGRAVATED", "AGGRAVATION", "ALARM",
        "ALARMED", "ALARMING", "ALARMINGLY", "ALIENATE", "ALIENATED", "ALIENATION",
        "ALLEGATION", "ALLEGATIONS", "ALLEGE", "ALLEGED", "ALLEGES", "ALLEGING",
        "ANNOYANCE", "ANNOYED", "ANNOYING", "ANNUL", "ANNULLED", "ANNULMENT", "ANTAGONIST",
        "ANTAGONISTIC", "ANXIETY", "ANXIOUS", "ANXIOUSLY", "APPREHENSION", "ARREST",
        "ARRESTED", "ARRESTS", "ASSAULT", "ASSAULTED", "ATROCIOUS", "AVERSE", "AVERSION",
        "BACKDATE", "BACKDATED", "BACKDATING", "BACKWARD", "BAD", "BADLY", "BAIL",
        "BAILOUT", "BAILOUTS", "BANKRUPT", "BANKRUPTED", "BANKRUPTCY", "BANKRUPTING",
        "BANKRUPTS", "BARRIERS", "BEAR", "BEARISH", "BETRAY", "BETRAYED", "BETRAYING",
        "BLAME", "BLAMED", "BLAMES", "BLAMING", "BLEAK", "BLINDSIDE", "BOTTLENECK",
        "BOTTLENECKS", "BOYCOTT", "BREACH", "BREACHED", "BREACHES", "BREACHING", "BRIBE",
        "BRIBED", "BRIBERY", "BRIBES", "BRIBING", "BURDEN", "BURDENED", "BURDENING",
        "CAUTION", "CAUTIONARY", "CAUTIOUS", "CAUTIOUSLY", "CEASE", "CEASED", "CEASING",
        "CENSURE", "CENSURED", "CHALLENGE", "CHALLENGED", "CHALLENGES", "CHALLENGING",
        "CHARGE", "CHARGED", "CHARGES", "CHEAT", "CHEATED", "CHEATING", "CLAIM", "CLAIMED",
        "CLAIMS", "CLOSE", "CLOSED", "CLOSING", "CLOSURE", "CLOSURES", "COLLAPSE",
        "COLLAPSED", "COLLAPSES", "COLLAPSING", "COLLUDE", "COLLUDED", "COLLUSION",
        "COMPLAIN", "COMPLAINED", "COMPLAINING", "COMPLAINT", "COMPLAINTS", "CONCEAL",
        "CONCEALED", "CONCEDE", "CONCEDED", "CONCERN", "CONCERNED", "CONCERNS", "CONFLICT",
        "CONFLICTED", "CONFLICTING", "CONFLICTS", "CONFRONT", "CONFRONTED", "CONFUSED",
        "CONFUSING", "CONFUSION", "CONTAMINATE", "CONTAMINATED", "CONTAMINATION", "CONTEND",
        "CONTENDED", "CONTENDING", "CONTEST", "CONTESTED", "CONTRADICT", "CONTRADICTED",
        "CONTRADICTION", "CONTRARY", "CONTROVERSIAL", "CONTROVERSY", "CONVICT", "CONVICTED",
        "CONVICTION", "CORRECT", "CORRECTED", "CORRECTION", "CORRUPT", "CORRUPTED",
        "CORRUPTING", "CORRUPTION", "COSTLY", "COUNTERFEIT", "COUNTERFEITING", "CRASH",
        "CRASHED", "CRASHES", "CRASHING", "CRIME", "CRIMES", "CRIMINAL", "CRISES", "CRISIS",
        "CRITICAL", "CRITICISM", "CRITICIZE", "CRITICIZED", "CRITICIZING", "DAMAGE",
        "DAMAGED", "DAMAGES", "DAMAGING", "DANGER", "DANGEROUS", "DEAD", "DEADLOCK",
        "DEADLOCKED", "DEADLOCKS", "DECEASED", "DECEIT", "DECEIVE", "DECEIVED", "DECEIVING",
        "DECLINE", "DECLINED", "DECLINES", "DECLINING", "DEFAULT", "DEFAULTED", "DEFAULTING",
        "DEFAULTS", "DEFEAT", "DEFEATED", "DEFEATS", "DEFECT", "DEFECTIVE", "DEFECTS",
        "DEFICIENCIES", "DEFICIENCY", "DEFICIENT", "DEFICITS", "DEFRAUD", "DEFRAUDED",
        "DELAY", "DELAYED", "DELAYING", "DELAYS", "DEMISE", "DENY", "DEPRESS", "DEPRESSED",
        "DEPRESSING", "DEPRESSION", "DESTROY", "DESTROYED", "DESTROYING", "DESTROYS",
        "DETRIMENT", "DETRIMENTAL", "DEVIATE", "DEVIATED", "DEVIATION", "DIFFICULT",
        "DIFFICULTIES", "DIFFICULTY", "DIMINISH", "DIMINISHED", "DIMINISHING", "DISAPPEAR",
        "DISAPPEARANCE", "DISAPPEARED", "DISAPPOINT", "DISAPPOINTED", "DISAPPOINTING",
        "DISAPPOINTMENT", "DISASTER", "DISASTROUS", "DISCLAIM", "DISCLAIMED", "DISCLOSE",
        "DISCONTINUE", "DISCONTINUED", "DISCOURAGE", "DISCOURAGED", "DISCREPANCY",
        "DISMAL", "DISMISS", "DISMISSED", "DISMISSING", "DISMISSAL", "DISPUTE", "DISPUTED",
        "DISPUTES", "DISPUTING", "DISRUPT", "DISRUPTED", "DISRUPTING", "DISRUPTION",
        "DISRUPTIONS", "DISSATISFACTION", "DISSATISFIED", "DISSENT", "DISTORTED",
        "DISTORTION", "DISTRESS", "DISTRESSED", "DIVEST", "DIVESTED", "DIVESTING",
        "DIVESTITURE", "DIVESTITURES", "DOUBT", "DOUBTED", "DOUBTFUL", "DOUBTS",
        "DOWNGRADE", "DOWNGRADED", "DOWNGRADES", "DOWNGRADING", "DOWNSIDE", "DOWNSIZE",
        "DOWNSIZED", "DOWNSIZING", "DOWNTURN", "DOWNTURNS", "DOWNWARD", "DOWNWARDS",
        "DRAWBACK", "DRAWBACKS", "DROP", "DROPPED", "DROPPING", "DROPS", "DUMP", "DUMPED",
        "DUMPING", "EARLY", "EMBARRASS", "EMBARRASSED", "EMBARRASSING", "EMBARRASSMENT",
        "EMBEZZLE", "EMBEZZLED", "EMBEZZLEMENT", "EMERGENCY", "ENDANGER", "ENDANGERED",
        "ERODE", "ERODED", "ERRONEOUS", "ERRONEOUSLY", "ERROR", "ERRORS", "EXAGGERATE",
        "EXAGGERATED", "EXCESSIVE", "EXCESSIVELY", "EXPLOIT", "EXPLOITATION", "EXPLOITED",
        "EXPLOITING", "EXPOSE", "EXPOSED", "EXPOSES", "EXPOSING", "FAIL", "FAILED",
        "FAILING", "FAILS", "FAILURE", "FAILURES", "FALSE", "FALSELY", "FAULT", "FAULTY",
        "FEAR", "FEARED", "FEARFUL", "FEARS", "FELONY", "FINE", "FINED", "FINES", "FLAW",
        "FLAWED", "FLAWS", "FORCE", "FORCED", "FORFEIT", "FORFEITED", "FRAUD", "FRAUDS",
        "FRAUDULENT", "FREEZE", "FROZEN", "FRUSTRATE", "FRUSTRATED", "FRUSTRATING",
        "FRUSTRATION", "HALT", "HALTED", "HALTING", "HAMPER", "HAMPERED", "HAMPERING",
        "HARASS", "HARASSED", "HARASSING", "HARASSMENT", "HARM", "HARMED", "HARMFUL",
        "HARMING", "HARMS", "HARSH", "HARSHLY", "HAZARD", "HAZARDOUS", "HAZARDS",
        "HINDER", "HINDERED", "HINDERING", "HURT", "HURTING", "IGNORE", "IGNORED",
        "IGNORING", "ILLEGAL", "ILLEGALITY", "ILLEGALLY", "ILLEGITIMATE", "ILLICIT",
        "IMPAIR", "IMPAIRED", "IMPAIRING", "IMPAIRMENT", "IMPAIRMENTS", "IMPEDE",
        "IMPEDED", "IMPEDING", "IMPOSE", "IMPOSED", "IMPOSES", "IMPOSITION", "INADEQUACY",
        "INADEQUATE", "INADEQUATELY", "INCAPABLE", "INCAPACITATED", "INCIDENT", "INCIDENTS",
        "INCOMPATIBLE", "INCOMPETENCE", "INCOMPETENT", "INCOMPLETE", "INCORRECT",
        "INCORRECTLY", "INDICTED", "INDICTMENT", "INDICTMENTS", "INEFFECTIVE", "INEFFICIENT",
        "INFERIOR", "INFRINGE", "INFRINGED", "INFRINGEMENT", "INFRINGING", "INJUNCTION",
        "INSOLVENCIES", "INSOLVENCY", "INSOLVENT", "INSUFFICIENT", "INSUFFICIENTLY",
        "INTERRUPT", "INTERRUPTED", "INTERRUPTION", "INTERRUPTIONS", "INTRUSION",
        "INVESTIGATE", "INVESTIGATED", "INVESTIGATING", "INVESTIGATION", "INVESTIGATIONS",
        "LACKING", "LACKLUSTER", "LAGGED", "LAGGING", "LATE", "LAWSUIT", "LAWSUITS",
        "LAYOFF", "LAYOFFS", "LIE", "LIED", "LIES", "LIMIT", "LIMITATION", "LIMITATIONS",
        "LIMITED", "LIMITING", "LIMITS", "LITIGATE", "LITIGATED", "LITIGATION", "LOSE",
        "LOSER", "LOSES", "LOSING", "LOSS", "LOSSES", "LOST", "MISHANDLE", "MISHANDLED",
        "MISLEAD", "MISLEADING", "MISLED", "MISMANAGE", "MISMANAGED", "MISMANAGEMENT",
        "MISREPRESENT", "MISREPRESENTATION", "MISREPRESENTED", "MISS", "MISSED", "MISSING",
        "MISSTATE", "MISSTATED", "MISSTATEMENT", "MISSTATEMENTS", "MISSTATING", "MISUSE",
        "MISUSED", "NEGATIVE", "NEGATIVELY", "NEGATIVES", "NEGLECT", "NEGLECTED",
        "NEGLIGENCE", "NEGLIGENT", "NONCOMPLIANCE", "NONCOMPLIANT", "NULL", "NULLIFIED",
        "NULLIFY", "OBSOLETE", "OBSTACLE", "OBSTACLES", "OMIT", "OMITTED", "OPPOSE",
        "OPPOSED", "OPPOSING", "OVERCHARGE", "OVERCHARGED", "OVERCHARGES", "OVERDUE",
        "OVERESTIMATE", "OVERESTIMATED", "OVERLOAD", "OVERLOADED", "OVERRUN", "OVERRUNS",
        "OVERSIGHT", "OVERSTATE", "OVERSTATED", "OVERSTATEMENT", "OVERTURN", "OVERTURNED",
        "PANIC", "PANICKED", "PANICS", "PENALIZE", "PENALIZED", "PENALIZES", "PENALIZING",
        "PENALTIES", "PENALTY", "PERMITTED", "PERSIST", "PLEAD", "PLEADED", "PLUNGE",
        "PLUNGED", "PLUNGES", "PLUNGING", "POOR", "POORER", "POORLY", "POSTPONE",
        "POSTPONED", "POSTPONING", "PREJUDICE", "PREJUDICED", "PROBLEM", "PROBLEMATIC",
        "PROBLEMS", "PROTEST", "PROTESTED", "PROTESTING", "PROTESTS", "PUNISH", "PUNISHED",
        "PUNISHES", "PUNISHING", "PUNISHMENT", "QUESTION", "QUESTIONABLE", "QUESTIONED",
        "QUESTIONING", "QUESTIONS", "REBUKE", "REBUKED", "RECALL", "RECALLED", "RECALLING",
        "RECALLS", "RECESSION", "RECESSIONARY", "RECESSIONS", "RECKLESS", "REDUCE",
        "REDUCED", "REDUCING", "REDUCTION", "REDUCTIONS", "REDUNDANCIES", "REDUNDANCY",
        "REDUNDANT", "REFUSAL", "REFUSE", "REFUSED", "REFUSES", "REFUSING", "REGRESS",
        "REGRESSION", "REJECT", "REJECTED", "REJECTING", "REJECTION", "REJECTS",
        "RELAPSE", "REPOSSESS", "REPOSSESSED", "RESIGN", "RESIGNED", "RESIGNATION",
        "RESTATED", "RESTATEMENT", "RESTATEMENTS", "RESTRAINT", "RESTRICT", "RESTRICTED",
        "RESTRICTING", "RESTRICTION", "RESTRICTIONS", "RESTRICTIVE", "RETRENCH",
        "RETRENCHED", "RETRENCHMENT", "RISK", "RISKIER", "RISKS", "RISKY", "SABOTAGE",
        "SABOTAGED", "SCANDAL", "SCANDALS", "SCRUTINIZE", "SCRUTINIZED", "SCRUTINY",
        "SEIZE", "SEIZED", "SEIZING", "SERIOUS", "SERIOUSLY", "SETBACK", "SETBACKS",
        "SEVER", "SEVERE", "SEVERED", "SEVERELY", "SEVERING", "SHORTAGE", "SHORTAGES",
        "SHORTFALL", "SHORTFALLS", "SHUT", "SHUTDOWN", "SHUTDOWNS", "SLOW", "SLOWDOWN",
        "SLOWDOWNS", "SLOWED", "SLOWER", "SLOWING", "SLUGGISH", "SLUMP", "SLUMPED",
        "SLUMPS", "STAGNANT", "STAGNATE", "STAGNATED", "STAGNATION", "STOLEN", "STOPPAGE",
        "STOPPAGES", "STRAIN", "STRAINED", "STRAINING", "STRAIT", "STRESS", "STRESSED",
        "STRESSES", "STRUGGLE", "STRUGGLED", "STRUGGLES", "STRUGGLING", "SUBPOENA",
        "SUBPOENAED", "SUBPOENAS", "SUED", "SUES", "SUFFER", "SUFFERED", "SUFFERING",
        "SUING", "SUSPEND", "SUSPENDED", "SUSPENDING", "SUSPENSION", "SUSPENSIONS",
        "SUSPICION", "SUSPICIONS", "SUSPICIOUS", "TERMINATE", "TERMINATED", "TERMINATING",
        "TERMINATION", "TERMINATIONS", "THREAT", "THREATEN", "THREATENED", "THREATENING",
        "THREATENS", "THREATS", "TOXIC", "TRAGEDY", "TRAP", "TRAPPED", "TROUBLE",
        "TROUBLED", "TROUBLES", "TUMBLE", "TUMBLED", "TUMBLES", "TUMBLING", "TURMOIL",
        "UNACCEPTABLE", "UNAPPROVED", "UNAUTHORIZED", "UNAVAILABLE", "UNAVOIDABLE",
        "UNCERTAIN", "UNCERTAINTIES", "UNCERTAINTY", "UNCLEAR", "UNCOLLECTIBLE",
        "UNDERESTIMATE", "UNDERESTIMATED", "UNDERPERFORM", "UNDERPERFORMED",
        "UNDERPERFORMING", "UNDERPERFORMS", "UNDERSTATE", "UNDERSTATED", "UNDERSTATEMENT",
        "UNDESIRABLE", "UNEASY", "UNEMPLOYED", "UNEMPLOYMENT", "UNEXPECTED", "UNEXPECTEDLY",
        "UNFAIR", "UNFAIRLY", "UNFAVORABLE", "UNFAVORABLY", "UNFORESEEN", "UNFORTUNATE",
        "UNFORTUNATELY", "UNFULFILLED", "UNINSURED", "UNINTENDED", "UNJUST", "UNJUSTLY",
        "UNLAWFUL", "UNLAWFULLY", "UNLICENSED", "UNLUCKY", "UNMET", "UNNECESSARY",
        "UNPAID", "UNPLANNED", "UNPREDICTABLE", "UNPROFITABLE", "UNQUALIFIED",
        "UNREASONABLE", "UNRELIABLE", "UNRESOLVED", "UNSAFE", "UNSATISFACTORY",
        "UNSATISFIED", "UNSATISFYING", "UNSOUND", "UNSTABLE", "UNSUCCESSFUL", "UNSUITABLE",
        "UNTRUE", "UNWANTED", "UNWELCOME", "UNWILLING", "UPSET", "VIOLATE", "VIOLATED",
        "VIOLATES", "VIOLATING", "VIOLATION", "VIOLATIONS", "VIOLENCE", "VIOLENT",
        "VOLATILE", "VOLATILITY", "WARN", "WARNED", "WARNING", "WARNINGS", "WARNS",
        "WEAK", "WEAKEN", "WEAKENED", "WEAKENING", "WEAKER", "WEAKNESS", "WEAKNESSES",
        "WEAKEST", "WORSE", "WORSEN", "WORSENED", "WORSENING", "WORST", "WRITEDOWN",
        "WRITEDOWNS", "WRITEOFF", "WRITEOFFS", "WRONG", "WRONGDOING", "WRONGFUL",
    ],
    # Uncertainty
    "UNCERTAINTY": [
        "ABLE", "AMBIGUITIES", "AMBIGUITY", "AMBIGUOUS", "ANTICIPATE", "ANTICIPATED",
        "ANTICIPATES", "ANTICIPATING", "ANTICIPATION", "APPARENT", "APPARENTLY", "APPEAR",
        "APPEARED", "APPEARING", "APPEARS", "APPROXIMATE", "APPROXIMATED", "APPROXIMATELY",
        "APPROXIMATING", "APPROXIMATION", "APPROXIMATIONS", "ARBITRARILY", "ARBITRARY",
        "ASSUME", "ASSUMED", "ASSUMES", "ASSUMING", "ASSUMPTION", "ASSUMPTIONS", "BELIEF",
        "BELIEFS", "BELIEVE", "BELIEVED", "BELIEVES", "BELIEVING", "CAUTION", "CAUTIOUS",
        "CLARIFICATION", "COULD", "CROSSROADS", "DEPEND", "DEPENDED", "DEPENDENCE",
        "DEPENDENCIES", "DEPENDENCY", "DEPENDENT", "DEPENDING", "DEPENDS", "DESTABILIZE",
        "DESTABILIZED", "DESTABILIZING", "DEVIATE", "DEVIATED", "DEVIATES", "DEVIATING",
        "DEVIATION", "DEVIATIONS", "DOUBT", "DOUBTED", "DOUBTFUL", "DOUBTS", "EXPOSURE",
        "EXPOSURES", "FLUCTUATE", "FLUCTUATED", "FLUCTUATES", "FLUCTUATING", "FLUCTUATION",
        "FLUCTUATIONS", "HIDDEN", "HINGED", "HINGES", "IMPRECISION", "INCOMPLETENESS",
        "INDEFINITE", "INDEFINITELY", "INDEFINITENESS", "INDETERMINABLE", "INDETERMINATE",
        "INEXACT", "INEXACTLY", "INSTABILITIES", "INSTABILITY", "INTANGIBLE", "INTANGIBLES",
        "LIKELIHOOD", "MAY", "MAYBE", "MIGHT", "NEARLY", "NONASSESSABLE", "OCCASIONALLY",
        "ORDINARILY", "PENDING", "PERHAPS", "POSSIBILITIES", "POSSIBILITY", "POSSIBLE",
        "POSSIBLY", "PREDICT", "PREDICTED", "PREDICTING", "PREDICTION", "PREDICTIONS",
        "PREDICTIVE", "PREDICTOR", "PREDICTORS", "PREDICTS", "PRELIMINARY", "PRESUMABLY",
        "PRESUME", "PRESUMED", "PRESUMES", "PRESUMING", "PRESUMPTION", "PRESUMPTIONS",
        "PROBABILISTIC", "PROBABILITIES", "PROBABILITY", "PROBABLE", "PROBABLY", "PROJECT",
        "PROJECTED", "PROJECTING", "PROJECTION", "PROJECTIONS", "PROJECTS", "REASSESS",
        "REASSESSED", "REASSESSING", "REASSESSMENT", "REASSESSMENTS", "RECALCULATE",
        "RECALCULATED", "RECALCULATING", "RECALCULATION", "RECALCULATIONS", "REEXAMINE",
        "REEXAMINED", "REEXAMINING", "RELIANCE", "RELIED", "RELIES", "RELY", "RELYING",
        "REVAMP", "REVAMPED", "REVAMPING", "REVISE", "REVISED", "REVISES", "REVISING",
        "REVISION", "REVISIONS", "RISK", "RISKED", "RISKIER", "RISKINESS", "RISKING",
        "RISKS", "RISKY", "ROUGHLY", "RUMORS", "SEEM", "SEEMED", "SEEMING", "SEEMINGLY",
        "SEEMS", "SOMETIMES", "SOMEWHAT", "SPECULATE", "SPECULATED", "SPECULATES",
        "SPECULATING", "SPECULATION", "SPECULATIONS", "SPECULATIVE", "SPECULATIVELY",
        "SUDDEN", "SUDDENLY", "SUGGEST", "SUGGESTED", "SUGGESTING", "SUGGESTS",
        "SUSCEPTIBILITY", "TENTATIVE", "TENTATIVELY", "TURBULENCE", "TURBULENT",
        "UNANTICIPATED", "UNCERTAIN", "UNCERTAINLY", "UNCERTAINTIES", "UNCERTAINTY",
        "UNCLEAR", "UNCONFIRMED", "UNDECIDED", "UNDEFINABLE", "UNDEFINED", "UNDESIGNATED",
        "UNDETECTABLE", "UNDETECTED", "UNDETERMINABLE", "UNDETERMINED", "UNDOCUMENTED",
        "UNEXPECTED", "UNEXPECTEDLY", "UNFAMILIAR", "UNFAMILIARITY", "UNFORECASTED",
        "UNFORESEEABLE", "UNFORESEEN", "UNGUARANTEED", "UNHEDGED", "UNIDENTIFIABLE",
        "UNIDENTIFIED", "UNKNOWN", "UNKNOWNS", "UNOBSERVABLE", "UNPLANNED", "UNPREDICTABILITY",
        "UNPREDICTABLE", "UNPREDICTABLY", "UNPREDICTED", "UNPROVEN", "UNQUANTIFIABLE",
        "UNQUANTIFIED", "UNREALIZABLE", "UNRECONCILED", "UNSEASONABLE", "UNSEASONABLY",
        "UNSETTLED", "UNSPECIFIC", "UNSPECIFIED", "UNSURE", "UNTESTED", "UNUSUAL",
        "UNUSUALLY", "UNWRITTEN", "VAGARIES", "VAGUE", "VAGUELY", "VAGUENESS", "VAGUER",
        "VAGUEST", "VARIABILITY", "VARIABLE", "VARIABLES", "VARIABLY", "VARIANCE",
        "VARIANCES", "VARIANT", "VARIANTS", "VARIATION", "VARIATIONS", "VARIED", "VARIES",
        "VARY", "VARYING", "VOLATILE", "VOLATILITIES", "VOLATILITY",
    ],
}


def download_or_fallback() -> dict:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    for url in SRAF_URLS:
        logger.info(f"Trying {url} ...")
        try:
            r = requests.get(url, timeout=60, headers={"User-Agent": "Mozilla/5.0"})
            r.raise_for_status()
            OUT.write_bytes(r.content)
            logger.info(f"  downloaded {len(r.content) // 1024}KB -> {OUT}")
            return {"status": "downloaded", "path": str(OUT)}
        except Exception as e:
            logger.warning(f"  failed: {e}")

    # Fallback: write a CSV from our curated fallback lists
    logger.warning("All SRAF URLs failed; writing fallback dictionary")
    with OUT.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["Word", "Negative", "Positive", "Uncertainty", "Litigious"])
        all_words = {}
        for cat, words in FALLBACK_WORDS.items():
            for wd in words:
                all_words.setdefault(wd, {"NEGATIVE": 0, "POSITIVE": 0, "UNCERTAINTY": 0, "LITIGIOUS": 0})
                all_words[wd][cat] = 1
        for wd, flags in sorted(all_words.items()):
            w.writerow([wd, flags["NEGATIVE"], flags["POSITIVE"], flags["UNCERTAINTY"], flags["LITIGIOUS"]])
    logger.info(f"  fallback dict written -> {OUT} ({sum(len(v) for v in FALLBACK_WORDS.values())} words)")
    return {"status": "fallback", "path": str(OUT)}


if __name__ == "__main__":
    result = download_or_fallback()
    print(result)
